// Generated by scripts/gen_icons.py from assets/icons/*.svg - do not edit
// by hand, regenerate instead. See IconOp's doc comment (icon_draw.h) for
// what each command's fields mean.
#pragma once

#include "ui/icon_draw.h"

namespace sz::ui::icons {

constexpr IconCmd kPenCmds[] = {
    {IconOp::MoveTo, 12.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 16.5000f, 3.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 18.0000f, 5.0000f, 2.1213f, -2.3562f, 0.7854f, 0.0000f},
    {IconOp::LineTo, 7.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 16.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 16.5000f, 3.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kPen = {kPenCmds, IM_ARRAYSIZE(kPenCmds)};

constexpr IconCmd kEraserCmds[] = {
    {IconOp::MoveTo, 7.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 2.6500f, 16.6500f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 3.3641f, 15.9500f, 1.0000f, 2.3662f, 3.9170f, 0.0000f},
    {IconOp::LineTo, 14.3000f, 3.6000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 15.0000f, 4.3141f, 1.0000f, -2.3462f, -0.7954f, 0.0000f},
    {IconOp::LineTo, 21.4000f, 9.3000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 20.6859f, 10.0000f, 1.0000f, -0.7754f, 0.7754f, 0.0000f},
    {IconOp::LineTo, 13.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kEraser = {kEraserCmds, IM_ARRAYSIZE(kEraserCmds)};

constexpr IconCmd kEraserRectCmds[] = {
    {IconOp::RoundedRect, 1.0000f, 1.0000f, 23.0000f, 23.0000f, 3.0000f, 0.0000f},
    {IconOp::MoveTo, 7.5000f, 17.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.6500f, 14.6500f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 5.4099f, 14.0000f, 1.0000f, 2.4340f, 3.8492f, 0.0000f},
    {IconOp::LineTo, 13.8000f, 4.6000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 14.4500f, 5.3599f, 1.0000f, -2.2784f, -0.8632f, 0.0000f},
    {IconOp::LineTo, 19.3000f, 8.8000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 18.5401f, 9.4500f, 1.0000f, -0.7076f, 0.7076f, 0.0000f},
    {IconOp::LineTo, 13.5000f, 16.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.0000f, 17.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.5000f, 17.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kEraserRect = {kEraserRectCmds, IM_ARRAYSIZE(kEraserRectCmds)};

constexpr IconCmd kCameraCmds[] = {
    {IconOp::MoveTo, 14.5000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.5000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 7.0000f, 7.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 7.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 4.0000f, 9.0000f, 2.0000f, -1.5708f, -3.1416f, 0.0000f},
    {IconOp::LineTo, 2.0000f, 18.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 4.0000f, 18.0000f, 2.0000f, 3.1416f, 1.5708f, 0.0000f},
    {IconOp::LineTo, 20.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 20.0000f, 18.0000f, 2.0000f, 1.5708f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 22.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 20.0000f, 9.0000f, 2.0000f, 0.0000f, -1.5708f, 0.0000f},
    {IconOp::LineTo, 17.0000f, 7.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 14.5000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::Circle, 12.0000f, 13.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kCamera = {kCameraCmds, IM_ARRAYSIZE(kCameraCmds)};

constexpr IconCmd kLayoutGridCmds[] = {
    {IconOp::RoundedRect, 3.0000f, 3.0000f, 10.0000f, 10.0000f, 1.5000f, 0.0000f},
    {IconOp::RoundedRect, 14.0000f, 3.0000f, 21.0000f, 10.0000f, 1.5000f, 0.0000f},
    {IconOp::RoundedRect, 3.0000f, 14.0000f, 10.0000f, 21.0000f, 1.5000f, 0.0000f},
    {IconOp::RoundedRect, 14.0000f, 14.0000f, 21.0000f, 21.0000f, 1.5000f, 0.0000f},
};
constexpr Icon kLayoutGrid = {kLayoutGridCmds, IM_ARRAYSIZE(kLayoutGridCmds)};

constexpr IconCmd kLayerDownCmds[] = {
    {IconOp::MoveTo, 12.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 5.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 19.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kLayerDown = {kLayerDownCmds, IM_ARRAYSIZE(kLayerDownCmds)};

constexpr IconCmd kLayerUpCmds[] = {
    {IconOp::MoveTo, 12.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 5.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 19.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kLayerUp = {kLayerUpCmds, IM_ARRAYSIZE(kLayerUpCmds)};

constexpr IconCmd kMoveCmds[] = {
    {IconOp::MoveTo, 5.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 2.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 5.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 2.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 15.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 22.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 19.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 22.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 19.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 2.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 22.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 12.0000f, 2.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 22.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kMove = {kMoveCmds, IM_ARRAYSIZE(kMoveCmds)};

constexpr IconCmd kCopyCmds[] = {
    {IconOp::RoundedRect, 9.0000f, 9.0000f, 22.0000f, 22.0000f, 2.0000f, 0.0000f},
    {IconOp::MoveTo, 5.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 4.0000f, 13.0000f, 2.0000f, 1.5708f, 3.1416f, 0.0000f},
    {IconOp::LineTo, 2.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 4.0000f, 4.0000f, 2.0000f, 3.1416f, 4.7124f, 0.0000f},
    {IconOp::LineTo, 13.0000f, 2.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 13.0000f, 4.0000f, 2.0000f, -1.5708f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kCopy = {kCopyCmds, IM_ARRAYSIZE(kCopyCmds)};

constexpr IconCmd kTrashCmds[] = {
    {IconOp::MoveTo, 3.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 8.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 8.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 10.0000f, 4.0000f, 2.0000f, 3.1416f, 4.7124f, 0.0000f},
    {IconOp::LineTo, 14.0000f, 2.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 14.0000f, 4.0000f, 2.0000f, -1.5708f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 16.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 19.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 16.0000f, 20.0000f, 2.0000f, 0.0000f, 1.5708f, 0.0000f},
    {IconOp::LineTo, 7.0000f, 22.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 7.0000f, 20.0000f, 2.0000f, 1.5708f, 3.1416f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kTrash = {kTrashCmds, IM_ARRAYSIZE(kTrashCmds)};

constexpr IconCmd kPlusCmds[] = {
    {IconOp::MoveTo, 12.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 19.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 5.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 19.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kPlus = {kPlusCmds, IM_ARRAYSIZE(kPlusCmds)};

constexpr IconCmd kXCmds[] = {
    {IconOp::MoveTo, 18.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 6.0000f, 18.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 6.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 18.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kX = {kXCmds, IM_ARRAYSIZE(kXCmds)};

constexpr IconCmd kUndoCmds[] = {
    {IconOp::MoveTo, 3.0000f, 7.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 13.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 13.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 21.0000f, 17.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 12.0000f, 17.0000f, 9.0000f, 0.0000f, -1.5708f, 0.0000f},
    {IconOp::ArcTo, 12.0092f, 17.0000f, 9.0000f, -1.5718f, -2.3019f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 13.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kUndo = {kUndoCmds, IM_ARRAYSIZE(kUndoCmds)};

constexpr IconCmd kRectangleCmds[] = {
    {IconOp::RoundedRect, 3.0000f, 3.0000f, 21.0000f, 21.0000f, 2.0000f, 0.0000f},
};
constexpr Icon kRectangle = {kRectangleCmds, IM_ARRAYSIZE(kRectangleCmds)};

constexpr IconCmd kLineCmds[] = {
    {IconOp::MoveTo, 6.0000f, 18.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kLine = {kLineCmds, IM_ARRAYSIZE(kLineCmds)};

constexpr IconCmd kTypeCmds[] = {
    {IconOp::MoveTo, 12.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 4.0000f, 7.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 5.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 5.0000f, 5.0000f, 1.0000f, 3.1416f, 4.7124f, 0.0000f},
    {IconOp::LineTo, 19.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 19.0000f, 5.0000f, 1.0000f, -1.5708f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0000f, 7.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kType = {kTypeCmds, IM_ARRAYSIZE(kTypeCmds)};

constexpr IconCmd kMinimizeCmds[] = {
    {IconOp::MoveTo, 6.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kMinimize = {kMinimizeCmds, IM_ARRAYSIZE(kMinimizeCmds)};

constexpr IconCmd kMaximizeCmds[] = {
    {IconOp::MoveTo, 9.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 3.0000f, 8.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 8.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 15.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 16.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.0000f, 8.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 15.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 21.0000f, 16.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 16.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 8.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.0000f, 16.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kMaximize = {kMaximizeCmds, IM_ARRAYSIZE(kMaximizeCmds)};

constexpr IconCmd kRestoreCmds[] = {
    {IconOp::MoveTo, 3.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 21.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 20.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 21.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 15.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 3.0000f, 21.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 4.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 15.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kRestore = {kRestoreCmds, IM_ARRAYSIZE(kRestoreCmds)};

constexpr IconCmd kMoreVerticalCmds[] = {
    {IconOp::Circle, 12.0000f, 5.0000f, 2.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::Circle, 12.0000f, 12.0000f, 2.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::Circle, 12.0000f, 19.0000f, 2.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kMoreVertical = {kMoreVerticalCmds, IM_ARRAYSIZE(kMoreVerticalCmds)};

constexpr IconCmd kTargetCmds[] = {
    {IconOp::Circle, 12.0000f, 12.0000f, 8.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::Circle, 12.0000f, 12.0000f, 1.3000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kTarget = {kTargetCmds, IM_ARRAYSIZE(kTargetCmds)};

constexpr IconCmd kNoteCmds[] = {
    {IconOp::MoveTo, 4.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 6.0000f, 6.0000f, 2.0000f, 3.1416f, 4.7124f, 0.0000f},
    {IconOp::LineTo, 16.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 16.0000f, 6.0000f, 2.0000f, -1.5708f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 14.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 6.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 6.0000f, 18.0000f, 2.0000f, 1.5708f, 3.1416f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 7.0000f, 10.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 13.0000f, 10.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 7.0000f, 14.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 11.0000f, 14.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kNote = {kNoteCmds, IM_ARRAYSIZE(kNoteCmds)};

constexpr IconCmd kPinCmds[] = {
    {IconOp::MoveTo, 8.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 16.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 10.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 10.0000f, 10.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 6.0000f, 14.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 6.0000f, 17.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 17.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 14.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 14.0000f, 10.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 14.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 12.0000f, 17.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 22.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kPin = {kPinCmds, IM_ARRAYSIZE(kPinCmds)};

constexpr IconCmd kSelectCmds[] = {
    {IconOp::MoveTo, 4.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 22.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 22.0000f, 9.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.0000f, 22.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.0000f, 22.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 13.0000f, 13.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kSelect = {kSelectCmds, IM_ARRAYSIZE(kSelectCmds)};

constexpr IconCmd kScissorsCmds[] = {
    {IconOp::Circle, 6.0000f, 6.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::Circle, 6.0000f, 18.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 20.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 8.1200f, 15.8800f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 14.4700f, 14.4800f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 8.1200f, 8.1200f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 12.0000f, 12.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kScissors = {kScissorsCmds, IM_ARRAYSIZE(kScissorsCmds)};

constexpr IconCmd kClipboardCmds[] = {
    {IconOp::RoundedRect, 8.0000f, 2.0000f, 16.0000f, 6.0000f, 1.0000f, 0.0000f},
    {IconOp::MoveTo, 16.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 18.0000f, 6.0000f, 2.0000f, -1.5708f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0000f, 20.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 18.0000f, 20.0000f, 2.0000f, 0.0000f, 1.5708f, 0.0000f},
    {IconOp::LineTo, 6.0000f, 22.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 6.0000f, 20.0000f, 2.0000f, 1.5708f, 3.1416f, 0.0000f},
    {IconOp::LineTo, 4.0000f, 6.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::ArcTo, 6.0000f, 6.0000f, 2.0000f, 3.1416f, 4.7124f, 0.0000f},
    {IconOp::LineTo, 8.0000f, 4.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kClipboard = {kClipboardCmds, IM_ARRAYSIZE(kClipboardCmds)};

constexpr IconCmd kKeyboardCmds[] = {
    {IconOp::RoundedRect, 2.0000f, 5.0000f, 22.0000f, 19.0000f, 2.0000f, 0.0000f},
    {IconOp::MoveTo, 5.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 6.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 9.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 10.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 13.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 14.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 17.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.5000f, 9.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::MoveTo, 8.0000f, 14.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 16.0000f, 14.5000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kKeyboard = {kKeyboardCmds, IM_ARRAYSIZE(kKeyboardCmds)};

constexpr IconCmd kSettingsCmds[] = {
    {IconOp::MoveTo, 9.9300f, 4.7900f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 10.4400f, 2.1200f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 13.5600f, 2.1200f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 14.0700f, 4.7900f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.6400f, 5.4400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 17.8800f, 3.9100f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0900f, 6.1200f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.5600f, 8.3600f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 19.2100f, 9.9300f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.8800f, 10.4400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 21.8800f, 13.5600f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 19.2100f, 14.0700f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 18.5600f, 15.6400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 20.0900f, 17.8800f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 17.8800f, 20.0900f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 15.6400f, 18.5600f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 14.0700f, 19.2100f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 13.5600f, 21.8800f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 10.4400f, 21.8800f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.9300f, 19.2100f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 8.3600f, 18.5600f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 6.1200f, 20.0900f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.9100f, 17.8800f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 5.4400f, 15.6400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.7900f, 14.0700f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 2.1200f, 13.5600f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 2.1200f, 10.4400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 4.7900f, 9.9300f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 5.4400f, 8.3600f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 3.9100f, 6.1200f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 6.1200f, 3.9100f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 8.3600f, 5.4400f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::LineTo, 9.9300f, 4.7900f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::EndSubpath, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f},
    {IconOp::Circle, 12.0000f, 12.0000f, 3.0000f, 0.0000f, 0.0000f, 0.0000f},
};
constexpr Icon kSettings = {kSettingsCmds, IM_ARRAYSIZE(kSettingsCmds)};

}  // namespace sz::ui::icons
